### ISSUE TITLE
Incorrect type annotation for key_columns in connect_to_table function

### ISSUE THREAD

**Issue by WSL0809** [erezsh/reladiff#15]
# Description

The `key_columns` parameter in the `connect_to_table` function has an incorrect type annotation. While it is currently annotated as `str`, the default value is `("id",)`, suggesting that `key_columns` should be either a tuple of strings or a single string.

# Expected Behavior

Update the type annotation of `key_columns` from `str` to `Union[Tuple[str, ...], str]` to accurately represent its intended type.
# Suggested Modification
```
def connect_to_table(
    db_info: Union[str, dict],
    table_name: Union[DbPath, str],
    key_columns: Union[Tuple[str, ...], str] = ("id",),
    thread_count: Optional[int] = 1,
    **kwargs,
) -> TableSegment:
    pass
```

**Comment by erezsh** [comment]
You're right, thanks! I'll fix it.

**Comment by erezsh** [comment]
Fixed
