### ISSUE TITLE
[Python] get_stats_dict() error on empty table

### ISSUE THREAD

**Issue by alex-mirkin** [erezsh/reladiff#29]
When comparing MySQL to Snowflake, the `get_stats_dict()` method produces an error when the MySQL table is empty and `allow_empty_tables=True`.

row 111 in diff_table.py:
`table1_count = self.info_tree.info.rowcounts[1]`
Error: `KeyError: 1`

Using reladiff 0.5.2 from PyPi, and also latest master.

**Comment by erezsh** [comment]
Thanks for reporting this! It was happening whenever both tables were empty. I was able to fix the issue, and it is now in `master`.
