### ISSUE TITLE
[Python API] max_threadpool_size parameter is not respected in MySQL

### ISSUE THREAD

**Issue by alexm-atbay** [erezsh/reladiff#34]
**Describe the bug**
Using the `diff_tables()` from the Python API with the max_threadpool_size parameter set (e.g., to 8) for a table comparison between MySQL and Snowflake
In MySQL, only a single query runs concurrently, while in Snowflake, all 8 queries are executed concurrently as expected.

Performance insights screenshot:
<img width="1582" alt="Screenshot 2024-08-21 at 17 52 53" src="https://github.com/user-attachments/assets/4a82d1f2-a84e-49c0-a3f6-8cbc9f29c7ff">

When running the same, from shell CLI - I see the correct behavior.

<img width="1577" alt="Screenshot 2024-08-21 at 17 57 47" src="https://github.com/user-attachments/assets/22de59e0-b013-4a89-9bad-70891e15f54b">

Python:
```
# create db connections
mysql_conn = connect(mysql_conn_details)
snowflake_conn = connect(snowflake_conn_details)

# create a connection to the table
table_seg_mysql = TableSegment(
    database=mysql_conn,
    table_path=table_path,
    key_columns=pk_col_list,
    extra_columns=extra_columns,
    case_sensitive=False
)
table_seg_snowflake = TableSegment(
    database=snowflake_conn,
    table_path=tuple(map(str.upper, table_path)),
    key_columns=pk_col_list,
    extra_columns=extra_columns,
    case_sensitive=False
)

for sign, row in diff_tables(
                    table_seg_mysql,
                    table_seg_snowflake,
                    max_threadpool_size=8,
                    bisection_factor=16
                ):
    print(sign, row)
```

Shell CLI:
```
> reladiff --run compare_mysql_to_snowflake__my_table -c col1 -c col2 --threads 8 --bisection-factor 16
```

**Comment by erezsh** [comment]
The `max_threadpool_size` controls the worker pool, but you also need to enable threads for your database driver. So: 

```python
mysql_conn = connect(mysql_conn_details, thread_count=8)
```

But I looked now and noticed that the documentation for [connect](https://reladiff.readthedocs.io/en/latest/python-api.html#reladiff.connect) is incomplete. I'll make sure to fix it. 

Here is the docstring for connect() from the code:

```
        """Connect to a database using the given database configuration.

        Configuration can be given either as a URI string, or as a dict of {option: value}.

        The dictionary configuration uses the same keys as the TOML 'database' definition given with --conf.

        thread_count determines the max number of worker threads per database,
        if relevant. None means no limit.

        Parameters:
            db_conf (str | dict): The configuration for the database to connect. URI or dict.
            thread_count (int, optional): Size of the threadpool. Ignored by cloud databases. (default: 1)
            shared (bool): Whether to cache and return the same connection for the same db_conf. (default: True)

        Note: For non-cloud databases, a low thread-pool size may be a performance bottleneck.
```

**Comment by alexm-atbay** [comment]
Thanks, it works!

**Comment by erezsh** [comment]
Glad to hear it!

And the docs for [connect](https://reladiff.readthedocs.io/en/latest/python-api.html#reladiff.connect) are now fixed.
